SET @CODEMPRESA = 1;
SET @CODDEPARTAMENTO = 3; 
SET @CODGRUPO = 2;
SET @DATAINICIAL = '2020-04-01';
SET @DATAFINAL = '2020-05-31';

SELECT E.CODENTRADA, E.CODEMPRESA, EM.NOME AS NOMEEMPRESA, E.CODDEPARTAMENTO, D.NOME AS NOMEDEPARTAMENTO, E.NUMERONOTA, 
P.CODGRUPO,  
DATE_FORMAT(E.DATARECEBIMENTO,'%d/%m/%Y') AS RECEBIMENTO, 
I.CODPRODUTO, P.NOME AS NOMEPRODUTO, I.QUANTIDADE 
FROM entrada E 
INNER JOIN entrada_item I ON I.CODENTRADA = E.CODENTRADA 
INNER JOIN produtos P ON P.CODPRODUTO = I.CODPRODUTO 
INNER JOIN empresa EM ON EM.CODEMPRESA = E.CODEMPRESA 
INNER JOIN departamento D ON D.CODDEPARTAMENTO = E.CODDEPARTAMENTO 
INNER JOIN fornecedor F ON F.CODFORNECEDOR = E.CODFORNECEDOR 

WHERE E.DATARECEBIMENTO BETWEEN @DATAINICIAL AND @DATAFINAL
AND E.CODEMPRESA = @CODEMPRESA
AND P.CODDEPARTAMENTO = @CODDEPARTAMENTO
AND P.CODGRUPO = @CODGRUPO
