SET @CODEMPRESA = 1;
SET @CODDEPARTAMENTO = 3; 
SET @DATAINICIAL = '2020-02-01';
SET @DATAFINAL = '2020-03-18';

SELECT P.CODEMPRESA, E.NOME AS NOMEEMPRESA, P.CODDEPARTAMENTO, D.NOME AS NOMEDEPARTAMENTO, P.CODUNIDADE, U.NOME AS NOMEUNIDADE, P.TIPO, 
P.CODPEDIDO, P.SOLICITANTE, P.NUMEROPEDIDO, 
PI.CODPRODUTO, PR.NOME AS NOMEPRODUTO, PI.QUANTIDADE,
P.DATAPEDIDO, P.`STATUS`
FROM pedido P
INNER JOIN empresa E ON E.CODEMPRESA = P.CODEMPRESA
INNER JOIN departamento D ON D.CODDEPARTAMENTO = P.CODDEPARTAMENTO
INNER JOIN unidade U ON U.CODUNIDADE = P.CODUNIDADE
INNER JOIN pedido_item PI ON PI.CODPEDIDO = P.CODPEDIDO
INNER JOIN produtos PR ON PR.CODPRODUTO = PI.CODPRODUTO

WHERE P.DATAPEDIDO BETWEEN @DATAINICIAL AND @DATAFINAL
AND P.CODEMPRESA = @CODEMPRESA
AND P.CODDEPARTAMENTO = @CODDEPARTAMENTO
AND P.CODPEDIDO = 37

ORDER BY P.CODPEDIDO, PR.NOME