SELECT P.CODPROTOCOLO, P.NUMEROPROTOCOLO, P.SITUACAO, DATE_FORMAT(P.DATASITUACAO,'%d/%m/%Y') AS DATASITUACAO, P.OBSERVACAO,
 P.CODPACIENTE, PC.NOME, DATE_FORMAT(PC.DATANASCIMENTO,'%d/%m/%Y') AS DATANASCIMENTO, PC.SEXO,
 PC.NUMEROSUS, PC.NOMEMAE, PC.ENDERECO, PC.BAIRRO, PC.TELEFONE, PC.CELL
FROM protocolo AS P
INNER JOIN paciente AS PC ON PC.CODPACIENTE = P.CODPACIENTE
